apiVersion: v1
kind: Service
metadata:
  name: surya-frontend-svc
  namespace: surya-ocr
  labels:
    app.kubernetes.io/name: surya-frontend
    app.kubernetes.io/component: web-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      protocol: TCP
  selector:
    app.kubernetes.io/name: surya-frontend
