apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: surya-ocr

resources:
  - namespace.yaml
  - configmap-secret.yaml
  - volumes-pvc.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-hpa.yaml
  - ingress-loadbalancer.yaml
  - backend-gpu-deployment.yaml
